<?xml version='1.0' encoding='UTF-8'?>
<tableParameters>
  <table>
    <name>HTML Table</name>
    <table>
      <name>table</name>
      <value>0</value>
    </table>
    <tgroup>
      <name>tgroup</name>
      <value>1</value>
    </tgroup>
    <title>
      <name>title</name>
      <value>1</value>
    </title>
    <thead>
      <name>thead</name>
      <value>2</value>
    </thead>
    <tbody>
      <name>tbody</name>
      <value>2</value>
    </tbody>
    <tfoot>
      <name>tfoot</name>
      <value>2</value>
    </tfoot>
    <row>
      <name>row</name>
      <value>3</value>
    </row>
    <entry>
      <name>entry</name>
      <value>4</value>
    </entry>
    <colspec>
      <name>colspec</name>
      <value>2</value>
    </colspec>
    <spanspec>
      <name>spanspec</name>
      <value>2</value>
    </spanspec>
    <entry-rowspan>
      <name>morerows</name>
      <value>0</value>
    </entry-rowspan>
    <entry-colspan>
      <name>namest, nameend</name>
      <value>-1</value>
    </entry-colspan>
    <colspec-num>
      <name>colnum</name>
      <value>-1</value>
    </colspec-num>
    <colspec-name>
      <name>colname</name>
      <value>-1</value>
    </colspec-name>
    <colspec-width>
      <name>colwidth</name>
      <value>-1</value>
    </colspec-width>
    <colspec-align>
      <name>align</name>
      <value>-1</value>
    </colspec-align>
    <colspec-colsep>
      <name>colsep</name>
      <value>-1</value>
    </colspec-colsep>
    <colspec-rowsep>
      <name>rowsep</name>
      <value>-1</value>
    </colspec-rowsep>
    <table-frame>
      <name>frame</name>
      <value>-1</value>
    </table-frame>
    <table-frame-values>
      <name>all,bottom,sides,top,topbot,none</name>
      <value>-1</value>
    </table-frame-values>
    <table-border>
      <name/>
      <value>-1</value>
    </table-border>
    <tgroup-cols>
      <name>cols</name>
      <value>-1</value>
    </tgroup-cols>
    <generate-id>
      <name>id</name>
      <value>1</value>
    </generate-id>
    <namespace>
      <name/>
      <value>1</value>
    </namespace>
  </table>
</tableParameters>
